name: core_model
description: This package provides model classes.
publish_to: "none"

environment:
  sdk: 3.6.1

resolution: workspace

dependencies:
  core_common: any
  freezed_annotation: 2.4.4
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.15
  freezed: 2.5.7
  riverpod_generator: 2.6.3
  test: 1.25.14
  yumemi_lints: 2.2.0
