name: "Build and Deploy to Cloud Run"

on:
  workflow_call:
    inputs:
      gar-location:
        type: string
        required: true
      project-id:
        type: string
        required: true
      repository:
        type: string
        required: true
      service:
        type: string
        required: true
    secrets:
      wif-provider:
        required: true
      wif-service-account:
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-24.04
    steps:
      - # https://github.com/marketplace/actions/checkout
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - # https://github.com/marketplace/actions/authenticate-to-google-cloud
        name: Google Auth
        id: auth
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.wif-provider }}'
          service_account: '${{ secrets.wif-service-account }}'

      - # https://github.com/marketplace/actions/docker-login
        name: Docker Auth
        id: docker-auth
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ inputs.gar-location }}-docker.pkg.dev'

      - # https://github.com/marketplace/actions/build-and-push-docker-images
        name: Build and push
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          context: .
          platforms: linux/amd64
          file: app/backend/Dockerfile
          push: true
          tags: |
            ${{ inputs.gar-location }}-docker.pkg.dev/${{ inputs.project-id }}/${{ inputs.repository }}/${{ inputs.service }}:latest

      - # https://github.com/marketplace/actions/deploy-to-cloud-run
        name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@9c5864eab7354d2e132307e685a2272655932799 # v2.7.3
        with:
          service: ${{ inputs.service }}
          region: ${{ inputs.gar-location }}
          image: ${{ inputs.gar-location }}-docker.pkg.dev/${{ inputs.project-id }}/${{ inputs.repository }}/${{ inputs.service }}:latest
